//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Cause_Project = new HashSet<Cause_Project>();
            this.SuitableLevel_Project = new HashSet<SuitableLevel_Project>();
            this.SuitableSubjects_Project = new HashSet<SuitableSubjects_Project>();
        }
    
        public int Id { get; set; }
        public string ProjectArea { get; set; }
        public string Description { get; set; }
        public string SpecificProjects { get; set; }
        public string Impact { get; set; }
        public string Skills { get; set; }
        public string SourceLink { get; set; }
        public string SuggestedReading { get; set; }
        public string SuggestedMethods { get; set; }
        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsApproved { get; set; }
        public string Title { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cause_Project> Cause_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuitableLevel_Project> SuitableLevel_Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuitableSubjects_Project> SuitableSubjects_Project { get; set; }
    }
}
