//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int Id { get; set; }
        public string ProjectArea { get; set; }
        public string Description { get; set; }
        public string SpecificProjects { get; set; }
        public string SuitableSubjects { get; set; }
        public string Cause { get; set; }
        public string SuitableLevel { get; set; }
        public string Skills { get; set; }
        public string TimeRequired { get; set; }
        public string Impact { get; set; }
        public string KeyContacts { get; set; }
        public string OtherContacts { get; set; }
        public string Source { get; set; }
        public string SuggestedReading { get; set; }
        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
