//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Project
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Field is required")]
        public string ProjectArea { get; set; }

        [Required(ErrorMessage ="Field is required")]
        public string Description { get; set; }
        public string SpecificProjects { get; set; }

        [Required(ErrorMessage = "Field is required")]
        public string Impact { get; set; }

        [Required(ErrorMessage = "Field is required")]
        public int SuitableSubjectId { get; set; }

        [Required(ErrorMessage = "Field is required")]
        public int CauseId { get; set; }

        [Required(ErrorMessage = "Field is required")]
        public string SuitableLevel { get; set; }
        public string Skills { get; set; }
        public string SourceLink { get; set; }
        public string SuggestedReading { get; set; }
        public string SuggestedMethods { get; set; }

        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Cause Cause { get; set; }
        public virtual SuitableSubject SuitableSubject { get; set; }
    }
}
